/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCascader: typeof import('./components/base/base-cascader.vue')['default']
    BaseDialog: typeof import('./components/base/base-dialog.vue')['default']
    BaseForm: typeof import('./components/base/base-form.vue')['default']
    BaseInput: typeof import('./components/base/base-input.vue')['default']
    BaseSelect: typeof import('./components/base/base-select.vue')['default']
    BaseTable: typeof import('./components/base/base-table.vue')['default']
    BaseVxeTable: typeof import('./components/base/base-vxe-table.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
